FROM ethereum/client-go:v1.10.11 as client-go

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.14

WORKDIR /app
EXPOSE 8545 8546 30303 30303/udp

RUN install_packages lsblk jq parted e2fsprogs e2fsprogs-extra hdparm prometheus-node-exporter

COPY --from=client-go /usr/local/bin/geth /usr/local/bin/
COPY scripts scripts

ENTRYPOINT [ "/bin/bash", "/app/scripts/entry.sh" ]

#dev-cmd-live=balena-idle
CMD [ "geth" ]