{
 "title": "Disk Usage",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "ethnode ( --datadir )", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/geth\"}/1024/1024/1024",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/geth\"}/1024/1024/1024",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/geth\"}/1024/1024/1024",
     "legendFormat": " Free"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/geth\"} - node_filesystem_avail_bytes{mountpoint=\"/geth\"})/1024/1024/1024",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/geth\"}/1024/1024/1024",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "description": "asdasd",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/geth\"} * 100) /          node_filesystem_size_bytes{mountpoint=\"/geth\"})",
     "legendFormat": " "
    }
   ]
  },
  { "title": "ethnode USB ( --datadir )", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/ethereum\"}/1024/1024/1024",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/ethereum\"}/1024/1024/1024",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/ethereum\"}/1024/1024/1024",
     "legendFormat": " Free"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/ethereum\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/ethereum\"})/1024/1024/1024",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/ethereum\"}/1024/1024/1024",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "description": "asdasd",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/ethereum\"} * 100) /          node_filesystem_size_bytes{mountpoint=\"/mnt/ethereum\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "ethancient USB ( --datadir.ancient )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/ethereum-ancient\"}/1024/1024/1024",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/ethereum-ancient\"}/1024/1024/1024",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/ethereum-ancient\"}/1024/1024/1024",
     "legendFormat": " Free"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/ethereum-ancient\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/ethereum-ancient\"})/1024/1024/1024",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/ethereum-ancient\"}/1024/1024/1024",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "description": "asdasd",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/ethereum-ancient\"} * 100) /          node_filesystem_size_bytes{mountpoint=\"/mnt/ethereum-ancient\"})",
     "legendFormat": " "
    }
   ]
  }
 ]
}