FROM balenablocks/dashboard:%%BALENA_ARCH%%-1.1.4

COPY ./geth.json /usr/share/grafana/conf/provisioning/dashboards
COPY ./disk-usage.json /usr/share/grafana/conf/provisioning/dashboards
COPY ./dashboards.yml /usr/share/grafana/conf/provisioning/dashboards
COPY ./prometheus-datasource.yml /usr/share/grafana/conf/provisioning/datasources
